### ISSUE TITLE
Error executing process > 'estimateStrainCountDesman (19)'

### ISSUE THREAD

**Issue by xif033** [chrisquince/DESMAN#35]
Hello, 

I am running desmanflow automated flow on my dataset. It works on most of my samples, but for a few samples I am getting the following error and I am wondering if you have recommendations to fix it : 

ERROR ~ Error executing process > 'estimateStrainCountDesman (19)'

Caused by:
  Process `estimateStrainCountDesman (19)` terminated with an error exit status (1)

Command executed:

  /home/xif033/tools/DESMAN//bin/desman outputsel_var.csv -e outputtran_df.csv -o cluster_9_2 -r 1000 -i 100 -g 9 -s 2 > cluster_9_2.out
  cp */fit.txt fit_9_2.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Up and running. Check cluster_9_2/log_file.txt for progress
  /home/xif033/.local/lib/python3.4/site-packages/desman-2.1.1-py3.4-linux-x86_64.egg/desman/Variant_Filter.py:74: FutureWarning: Method .as_matrix will be removed in a future version. Use .va
lues instead.
    variants_matrix = variants.as_matrix()
  /home/xif033/.local/lib/python3.4/site-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
    out=out, **kwargs)
  Traceback (most recent call last):
    File "/home/xif033/tools/DESMAN//bin/desman", line 246, in <module>
      main(sys.argv[1:])
    File "/home/xif033/tools/DESMAN//bin/desman", line 95, in main
      min_coverage=min_coverage, qvalue_cutoff=max_qvalue)
    File "/home/xif033/.local/lib/python3.4/site-packages/desman-2.1.1-py3.4-linux-x86_64.egg/desman/Variant_Filter.py", line 81, in __init__
      vs_mean = np.mean(vs_sum,axis=0)
    File "/home/xif033/.local/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 2920, in mean
      out=out, **kwargs)
    File "/home/xif033/.local/lib/python3.4/site-packages/numpy/core/_methods.py", line 78, in _mean
      ret, rcount, out=ret, casting='unsafe', subok=False)
  ZeroDivisionError: division by zero

Work dir:
  /oasis/projects/nsf/csd465/xif033/scripts/DESMAN/work/8d/36dd7b4706010e6adf6e24fc00696f

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details
WARN: Killing pending tasks (24)

I'd really appreciate any suggestions! 
Best,
Xin

**Comment by koadman** [comment]
Hi Xin, can you post the contents of the following files please:
/oasis/projects/nsf/csd465/xif033/scripts/DESMAN/work/8d/36dd7b4706010e6adf6e24fc00696f/outputsel_var.csv 
/oasis/projects/nsf/csd465/xif033/scripts/DESMAN/work/8d/36dd7b4706010e6adf6e24fc00696f/outputtran_df.csv

either here if it is small or somewhere else and then send a link please?

One issue we've seen previously is that the workflow fails with an error when there are no variants in the 37 universal genes. Knowing what's in those files will help tell us whether that's the problem, or if it's something else.

**Comment by xif033** [comment]
Hello Aaron,

Here's the content of the files: 
In /oasis/projects/nsf/csd465/xif033/scripts/DESMAN/work/8d/36dd7b4706010e6adf6e24fc00696f/outputsel_var.csv: 
,Position,2-A,2-C,2-G,2-T,3-A,3-C,3-G,3-T,4-A,4-C,4-G,4-T,5-A,5-C,5-G,5-T,7-A,7-C,7-G,7-T,9-A,9-C,9-G,9-T

In /oasis/projects/nsf/csd465/xif033/scripts/DESMAN/work/8d/36dd7b4706010e6adf6e24fc00696f/outputtran_df.csv
,0,1,2,3
0,0.9974489795918368,0.0004917629702483403,0.0014138185394639783,0.0006454388984509467
1,0.0008871214438666259,0.9971550933007036,0.00042826552462526765,0.0015295197308045274
2,0.0010059135523989514,0.0005486801194903372,0.9973480460891301,0.0010973602389806744
3,0.0008564087924636027,0.001284613188695404,0.0005709391949757351,0.9972880388238653

Please advise! Thanks a lot!
Xin
